---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: target
  name: target
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: target
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: target
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target
  template:
    metadata:
      labels:
        app: target
    spec:
      containers:
      - name: nginx
        image: nginx
